### ISSUE TITLE
No loot when planting drug crop

### ISSUE THREAD

**Issue by Xen0Xys** [xxCoderforlife/Simple-Drugs#39]
**Describe the bug**
When breaking a drug crop, it give no loot:
- If not growth it not give back the seed (just a normal seed)
- If growth with bonemeal it give normal seed and wheat

**To Reproduce**
1. Craft a drug seed (here Coke seed)
2. Plant it
3. Use bonemeal to fully growth it
4. Break the plant and see it only give normal seed and Wheat

**Expected behavior**
Get coke drug when breaking the crop.

- 2.7.3 DEV
- Paper: git-Paper-187

**Comment by SpaceXElaborator** [comment]
Found issue. While the item that represented the DrugPlantItem.class is correct based off the GsonAdapter. The GsonAdapter loaded in the non-persistent item from the json file as the DrugPlantItem's Recipe Result. Instead of the DrugPlantItem's makeItem() method used to add the PersistentDataContainer attributes.

Fixed with commit: https://github.com/xxCoderforlife/Simple-Drugs/commit/6bf53eef3ec050d8a6ca4fc4004c236555083466
